= Gatling tests for James server

image:https://travis-ci.org/linagora/james-gatling.svg?branch=master["Build Status", link="https://travis-ci.org/linagora/james-gatling"]

For now, you need to have a running dockerized James JMAP server running on the same computer than your Gatling host. It needs to export the webAdmin over port 8000.

Alternativly you can set up the following system properties:

 * `TARGET_HOSTNAME` which is set to `localhost` by default
 * `SMTP_PORT` which is set to `25` by default
 * `SMTP_SSL_PORT` which is set to `465` by default
 * `JMAP_PORT` which is set to `1080` by default
 * `JMAP_PROTOCOL` which is set to `http` by default (you can use `https` instead for example)
 * `WEBADMIN_PORT` which is set to `8000` by default
 * `WEBADMIN_PROTOCOL` which is set to `http` by default (you can use `https` instead for example)

In some cases you could want to specify target hostname per protocol, the following properties can help you:
 * `SMTP_TARGET_HOSTNAME` which is set to `TARGET_HOSTNAME` by default
 * `JMAP_TARGET_HOSTNAME` which is set to `TARGET_HOSTNAME` by default
 * `IMAP_SERVER_HOSTNAME` which is set to `TARGET_HOSTNAME` by default
 * `WEBADMIN_SERVER_HOSTNAME` which is set to `TARGET_HOSTNAME` by default

You can also customize the sizing of the scenarios:
 * `INJECT_DURATION` is the ramp up time, set to `10` seconds by default
 * `SCENARIO_DURATION` is the effective scenario duration, set to `10` seconds by default
 * `USER_COUNT` is the number of users, set to `100` by default
 * `RANDOMLY_SENT_MAILS` is the numbers of emails sent by user during the provisioning, `10` by default
 * `NUMBER_OF_MAILBOXES` is the numbers of mailboxes created during the provisioning, `10` by default
 * `NUMBER_OF_MESSAGES` is the numbers of messages created per mailbox during the provisioning, `20` by default

You can run all the simulations via sbt :

.bash
----
$ sbt
 > gatling:test
----

Run a specific simulation via sbt :

.bash
----
$ sbt
 > gatling:testOnly SIMULATION_FQDN
----

== Available simulations

=== JMAP draft

==== JmapAuthenticationSimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.jmap.draft.JmapAuthenticationSimulation
----

Authenticate 10 JMAP users, one time. Demonstrate user auto-provisioning through James WebAdmin server.

==== JmapSendMessagesSimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.jmap.draft.JmapSendMessagesSimulation
----

Authenticate 100 JMAP users, one time. Then they all retrieve their mailboxes, and then sends messages 360 messages each to other recipients.

==== JmapGetMailboxesSimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.jmap.draft.JmapGetMailboxesSimulation
----

Authenticate 200 JMAP users, one time. Then they all retrieve 360 times their mailboxes each.

==== JmapGetMessageListSimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.jmap.draft.JmapGetMessageListSimulation
----

Authenticate 100 JMAP users, one time. Then they all retrieve their system mailboxes. Then they send each other 10 mails each at random. Then wait 30 seconds for mails to be delivered. Finally they retrieve 250 times each their mails list using GetMessagesList.

==== JmapGetMessagesSimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.jmap.draft.JmapGetMessagesSimulation
----

Authenticate 100 JMAP users, one time. Then they all retrieve their system mailboxes. Then they send each other 10 mails each at random. Then wait 30 seconds for mails to be delivered. They retrieve their mails list using GetMessagesList. Then they retrieve their mails 250 times, at random.

==== JmapMessageUpdateSimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.jmap.draft.JmapMessageUpdateSimulation
----

Authenticate 100 JMAP users, one time. Then they all retrieve their system mailboxes. Then they send each other 10 mails each at random. Then wait 30 seconds for mails to be delivered. They retrieve their mails list using GetMessagesList. Then they update their mail 250 times with the following properties :.

 - 70% mark mails as READ
 - 20% mark mails as ANSWERED
 - 10% mark mails as FLAGGED

=== JMAP RFC-8621

==== MailboxGetSimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.jmap.rfc8621.MailboxGetSimulation
----

Authenticate 200 JMAP users, one time. Then they all retrieve 360 times their mailboxes each.

=== SMTP

==== SmtpNoAuthenticationNoEncryptionMixedBodySimulation

FQDN :

.scala
----
org.apache.james.gatling.simulation.smtp.SmtpNoAuthenticationNoEncryptionMixedBodySimulation
----

Create 100 users, one time. Then they all send mails to their self, every seconds, using SMTP, without encryption and without authentication.
